### ISSUE TITLE
Shift the shell script to a high level language like python or java

### ISSUE THREAD

**Issue by raul1991** [raul1991/monito#24]
This would ease the development and error handling

**Comment by cjwilburn** [comment]
Which shell script do you want changed, the main `monito.sh` , `send_mail.sh`, or both?

**Comment by cjwilburn** [comment]
I may be able to take this on.

**Comment by raul1991** [comment]
I was thinking of using fabric (pip package) for the ssh thing.

**Comment by cjwilburn** [comment]
that makes sense. i'd still like to take this one, if that's okay.

**Comment by raul1991** [comment]
Go ahead. @cjwilburn

**Comment by raul1991** [comment]
Fabric and python based pinger script is in place. Read the readme for more details.
