### ISSUE TITLE
Use snackbars for information display

### ISSUE THREAD

**Issue by raul1991** [raul1991/monito#37]
Bootstrap snackbars can be integrated for messages. Create a common helper method that can be invoked from any js file for showing the message.

signature can be something like

timeout, message, type (danger,warn,info)

**Comment by bekicelmir** [comment]
Hi. I'll try this and open PR once it's ready

**Comment by raul1991** [comment]
Sure. Go ahead.

**Comment by raul1991** [comment]
#57
